### ISSUE TITLE
Unable to build the template-node

### ISSUE THREAD

**Issue by vyorkin** [substrate-developer-hub/substrate-how-to-guides#78]
Hello! I'm trying to build the `template-node` (`main` branch)
```
$ cargo run --release

error: failed to download `parity-db v0.2.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/vyorkin/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11 ` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
```

If I remove the `Cargo.lock` then it is unable to resolve a version for `snow` crate:

```
$ cargo run --release -- --dev --tmp

    Updating crates.io index
error: failed to select a version for `snow`.
    ... required by package `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-cli v0.9.0`
    ... which is depended on by `frame-benchmarking-cli v3.0.0`
    ... which is depended on by `node-template v3.0.0 (/home/vyorkin/projects/play/rust/substrate/how-to-guides/example-code/template-node/node)`
versions that meet the requirements `^0.7.1` are: 0.7.2, 0.7.1

all possible versions conflict with previously selected packages.

  previously selected package `snow v0.7.1`
    ... which is depended on by `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-cli v0.9.0`
    ... which is depended on by `frame-benchmarking-cli v3.0.0`
    ... which is depended on by `node-template v3.0.0 (/home/vyorkin/projects/play/rust/substrate/how-to-guides/example-code/template-node/node)`

failed to select a version for `snow` which could resolve this conflict
```

My `rustup show` output:

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/vyorkin/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-10-25-x86_64-unknown-linux-gnu
nightly-2021-01-25-x86_64-unknown-linux-gnu
nightly-2021-01-26-x86_64-unknown-linux-gnu
nightly-2021-03-15-x86_64-unknown-linux-gnu
nightly-2021-05-20-x86_64-unknown-linux-gnu
nightly-2021-06-01-x86_64-unknown-linux-gnu
nightly-2021-06-17-x86_64-unknown-linux-gnu
nightly-2021-06-29-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.34.1-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu
1.50.0-x86_64-unknown-linux-gnu
1.51.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```

EDIT 1:

Updating `parity-db` from `0.2.3` to `0.2.4` helps.
https://github.com/paritytech/substrate/issues/8161#issuecomment-895695913

But I got another error related to `pallet_kitties`:

```
  error[E0437]: type `Randomness` is not a member of trait `pallet_kitties::Config`
     --> /home/vyorkin/projects/play/rust/substrate/how-to-guides/example-code/template-node/runtime/src/lib.rs:296:2
      |
  296 |     type Randomness = RandomnessCollectiveFlip;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `pallet_kitties::Config`

  error[E0046]: not all trait items implemented, missing: `KittyRandomness`
     --> /home/vyorkin/projects/play/rust/substrate/how-to-guides/example-code/template-node/runtime/src/lib.rs:294:1
      |
  294 | impl pallet_kitties::Config for Runtime {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `KittyRandomness` in implementation
      |
      = help: implement the missing item: `type KittyRandomness = Type;`
```

Possibly related to #36

**Comment by vyorkin** [comment]
Nvm, local machine issues %)
Resolved by updating the `parity-db` crate https://github.com/paritytech/substrate/issues/8161#issuecomment-895695913

**Comment by sacha-l** [comment]
Hi @vyorkin - thanks for bringing this to my attention. Sorry that you've been having trouble with this. It's not your fault its mainly because of two reasons:
- the `template-node` is outdated (i.e. it's not following Substrate's latest release)
- the `template-node` is not meant to be run as is. It is more designed house the different pallets that some how-to guides refer to. For example, `mint-token`, `reward-coin` etc etc. This way, the code examples exist as a reference and can be configured inside the template if need be. We're working on migrating this content to an improved framework and making these nuances clearer for how-to guides.

The usage of the example code should really just be to cross reference guides, rather than trying to run a working node. That being said, its a good exercise to integrate the pallets in the `example-code` folder into your local node for learning. 

The issue you're having specific to the `kitties` pallet is explained [here](https://github.com/substrate-developer-hub/substrate-how-to-guides/issues/36#issuecomment-881035865) yes. I recommend you try [the Kitties tutorial](https://substrate.dev/substrate-how-to-guides/docs/tutorials/Kitties/overview). It's completely new and improved ✨ 😎 .

As a follow up to this, I'm going to remove the `kitties` pallet from the example code repo and add a brief explanation on the intended usage of the `example-code` folder. 👍🏻

**Comment by sacha-l** [comment]
Seems like the issue is fixed. Please re-open if otherwise.
